---
- name: Import Microsoft Key
  become: yes
  ansible.builtin.rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc

- name: Add YUM Repo
  become: yes
  yum_repository:
    name: vscode
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Install
  become: yes
  dnf:
    name: code
    state: present
