color=#E0E0E0

#[weather]
#command=curl -Ss 'https://wttr.in?0&T&Q' | cut -c 16- | head -2 | xargs echo
#interval=3600

[date]
command=date '+%B %d - %I:%M %p'  # July 06 - 12:52 AM
interval=1
label= 
