---
- name: Install packages
  become: yes

  dnf:
    name: "{{ item.key }}"
    state: "{{ item.value.state | default('present') }}"

  with_dict: "{{dnf}}"
  vars:
    dnf:
      fzf:
      git:
      jq:
      jc:
      zsh:

- name: Ensure shell is default for user
  vars:
    current_user: "{{ ansible_user_id }}"
  become: yes
  user:
    name: "{{ current_user }}"
    shell: /usr/bin/zsh

- name: Link configuration
  file:
    src: "{{ role_path }}/files/.zshrc"
    dest: "{{ lookup('env', 'HOME') }}/.zshrc"
    state: link

- name: Create folders
  file:
    path: "{{item}}"
    state: directory
  loop:
    - "{{ lookup('env', 'HOME') }}/src"
    - "{{ lookup('env', 'HOME') }}/bin"
