---
- name: Create folders for dotfiles
  file:
    path: "{{item}}"
    state: directory
  loop:
    - "$HOME/.config/nvim/autoload"
    - "$HOME/.gnupg"

- name: Link shared dotfiles
  file:
    src: "{{ item.value.src }}"
    dest: "{{ item.value.dest }}"
    state: link
  with_dict: "{{dotfiles}}"
  vars:
    dotfiles:
      zshrc:
        src: "{{playbook_dir}}/configs/shared/.zshrc"
        dest: "{{ lookup('env', 'HOME') }}/.zshrc"

      gitconfig:
        src: "{{playbook_dir}}/configs/shared/.gitconfig"
        dest: "{{ lookup('env', 'HOME') }}/.gitconfig"

      gdbinit:
        src: "{{playbook_dir}}/configs/shared/.gdbinit"
        dest: "{{ lookup('env', 'HOME') }}/.gdbinit"

      vimrc:
        src: "{{playbook_dir}}/configs/shared/nvim/init.vim"
        dest: "{{ lookup('env', 'HOME') }}/.config/nvim/init.vim"

      tmux:
        src: "{{playbook_dir}}/configs/shared/.tmux.conf"
        dest: "{{ lookup('env', 'HOME') }}/.tmux.conf"

      alacritty:
        src: "{{playbook_dir}}/configs/shared/alacritty"
        dest: "{{ lookup('env', 'HOME') }}/.config/alacritty"

      i3:
        src: "{{playbook_dir}}/configs/shared/i3"
        dest: "{{ lookup('env', 'HOME') }}/.config/i3"
