### Variables
#
# Logo key. Use Mod1 for Alt.
set $mod Mod4
set $alt Mod1

#
# Home row direction keys, like vim
#
set $left h
set $down j
set $up k
set $right l

#
# Terminal emulator to use
#
set $term termite

#
# Application launcher
#
#set $menu $term --name=launcher -e \
#     "bash -c 'compgen -c | sort -u | fzf | xargs -r swaymsg -t command exec'"
# set $menu j4-dmenu-desktop --dmenu="bemenu-run -l 30" --term="termite" --no-generic
set $menu wofi --show=drun --width=400 --lines=5

### Font configuration
#
font pango: Inter 18

### Idle configuration
#
# This will lock the screen after 300 seconds of inactivity, then turn off
# the displays after another 300 seconds, and turn your screens back on
# when resumed. It will also lock your screen before the computer goes to
# sleep.
#exec swayidle -w \
#     timeout 300 '$HOME/.local/bin/lockscreen' \
#     timeout 600 'swaymsg "output * dpms off"' resume 'swaymsg "output * dpms on"' \
#     before-sleep '$HOME/.local/bin/lockscreen'
