### Output configuration
#
# You can get the names of your outputs by running: swaymsg -t get_outputs
#

#
# Set wallpaper
#
output * bg $HOME/.config/wallpapers/5k-big-sur-color-day.jpg fill

#
# Set display and resolution
#
output DP-1 resolution 3840x2160 position 3840,0