#
# On Startup
#

#
# Use gammastep to change the display color at
# night so there is less blue light.
#
exec --no-startup-id gammastep -m wayland -l 43.5:-96.7 -t 6500:3500

#
# Startup pulseaudio so audio works.
#
exec --no-startup-id pulseaudio -D --start --system

#
# Start notification daemon
#
exec --no-startup-id dunst
