#
# On Startup
#

#
# Use gammastep to change the display color at
# night so there is less blue light.
#
exec gammastep -m wayland -l 43.5:-96.7 -t 6500:3000 -b 1.0:.7

#
# Start notification daemon
#
exec mako

#
# Start polkit authorization for GUI apps
#
exec /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

#
# Exec wob for volume displays
#
exec mkfifo $SWAYSOCK.wob && tail -f $SWAYSOCK.wob | wob
