---
- name: Install dnf core plugins
  become: yes
  dnf:
    name: dnf-plugins-core
    state: present

- name: Add repo
  become: yes
  shell: |
    dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo

- name: Install
  become: yes

  dnf:
    name: "{{ item.key }}"
    state: "{{ item.value.state | default('present') }}"

  with_dict: "{{packages}}"
  vars:
    packages:
      docker-ce:
      docker-ce-cli:
      containerd.io:
      docker-compose-plugin:

- name: Add current user to docker group
  become: yes
  ansible.builtin.user:
    append: yes
    name: "{{ ansible_user_id }}"
    groups: docker
