---
- name: Add Hack font COPR repo
  become: yes
  community.general.copr:
    host: copr.fedorainfracloud.org
    state: enabled
    name: zawertun/hack-fonts

- name: Install
  become: yes
  dnf:
    name: hack-fonts
    state: present
